import utils from '@/uni_modules/uni-ai-x/sdk/utils.uts'
type OnMsgFn = (e : UTSJSONObject) => void
type WebviewEvalTarget = {
	evalJS: (code: string) => void
}
class ProxyWeb {
	isInit : boolean = false
	private webviewContext : WebviewContext | WebviewEvalTarget | null = null
	callbackMap : Map<string, OnMsgFn> = new Map()
	constructor() {
		// #ifdef WEB
		window.addEventListener('message', (event) => {
			if (event.data?.data?.name == 'postMessage') {
				this.emitMsg(event.data.data.arg)
			}
		}, false)
		// #endif
	}
	callMethod(param : UTSJSONObject, callback : OnMsgFn) {
		// 先判断 isInit 是否为 true
		if (this.isInit == false) {
			setTimeout(() => {
				this.callMethod(param, callback)
			}, 1000)
			return
		}
		const requestId = Date.now() + Math.random().toString(36).substring(2, 15)
		param['requestId'] = requestId
		const key = (param['action'] as string) + '_callback_' + requestId
		this.callbackMap.set(key, callback)

		const code = `onMessage("${encodeURIComponent(JSON.stringify(param))}")`;
		// #ifdef APP
		utils.runOnDispatcher('main', () => {
			(this.webviewContext as WebviewEvalTarget | null)?.evalJS(code)
		})
		// #endif
		// #ifdef WEB
			(this.webviewContext as any)?.contentWindow.eval(code)
		// #endif
	}
	init(webviewContext : WebviewContext | WebviewEvalTarget) {
		this.webviewContext = webviewContext
	}
	onWebMsg(e : UniWebViewMessageEvent) {
		const event = e.detail.data[0] as UTSJSONObject
		const action = event['action'] as string
		const param = event['param'] as UTSJSONObject
		this.emitMsg({
			action,
			param
		})
	}
	emitMsg(res : UTSJSONObject) {
		if (res['action'] == 'DOMContentLoaded_callback') {
			this.isInit = true
			return
		}
		const funName = res['action']! as string
		const callback = this.callbackMap.get(funName)
		if (callback == null) {
			console.error('callback is null', funName)
			return
		}
		this.callbackMap.delete(funName)
		utils.runOnDispatcher('io',()=>{
			callback(res['param'] as UTSJSONObject)
		})
	}
}
export default new ProxyWeb()
