import { MarkdownToken } from '@/uni_modules/uni-cmark/utssdk/interface.uts'
class Utils {
	getTokensText(tokens?: MarkdownToken[]){
		if (tokens == null) return ''
		let text = ''
		tokens.forEach((token: MarkdownToken)=>{
			if(token.text != null){
				text += token.text
			}else if(token.tokens != null && token.tokens.length > 0){
				text += this.getTokensText(token.tokens)
			}
		})
		return text
	}
	// 把 UTSAndroid.getDispatcher("io").async((_) => 封装成一个函数
	uniGetDispatcher(taskName : string, fn : () => void) {
		// #ifdef APP-ANDROID
		try {
			UTSAndroid.getDispatcher(taskName).async((_) => {
				fn()
			})
		} catch (error) {
			// 蒸汽模式 JS 引擎版下可能不存在 UTSAndroid，直接回退为当前线程执行。
			fn()
		}
		// #endif
		// #ifndef APP-ANDROID
		fn()
		// #endif
	}
}
export default new Utils()
