import { MainActivity } from 'com.dcloud.cmark'

let cmarkInstance: MainActivity | null = null

export function initMd2html(): Promise<void> {
	return Promise.resolve()
}

function getCmarkInstance(): MainActivity {
	if (cmarkInstance == null) {
		cmarkInstance = new MainActivity()
	}
	return cmarkInstance!
}

export function md2html(markdown: string): string {
	return getCmarkInstance().md2html(markdown)
}

export function isMd2htmlAvailable(): boolean {
	return getCmarkInstance().isMd2htmlAvailable()
}
